ALTER TABLE "Teacher" ADD COLUMN "bankName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Teacher" ADD COLUMN "bankCode" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Teacher" ADD COLUMN "bankBranch" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Teacher" ADD COLUMN "bankAccountName" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Teacher" ADD COLUMN "bankAccountNumber" TEXT NOT NULL DEFAULT '';
